---
- name: Generar respaldo del router CSR1000v
  hosts: routers
  gather_facts: false
  
  tasks:
    - name: Ejecutar comando show running-config
      ios_command:
        commands: show running-config
      register: salida_config

    - name: Guardar la configuracion en un archivo de texto
      copy:
        content: "{{ salida_config.stdout[0] }}"
        dest: "./respaldo_csr1000v.txt"